apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
  labels:
    app: angular-app
spec:
  selector:
    app: angular-app
  ports:
  - name: http
    protocol: TCP
    port: 8093
    targetPort: 80
  type: LoadBalancer